# Generated by Django 6.0 on 2025-12-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_id', models.IntegerField()),
                ('cours_titre', models.CharField(max_length=200)),
                ('auteur_id', models.IntegerField()),
                ('auteur_email', models.EmailField(max_length=254)),
                ('auteur_nom', models.CharField(max_length=100)),
                ('auteur_prenom', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_message', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
