# Generated by Django 6.0 on 2025-12-08 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('niveau', models.CharField(max_length=50)),
                ('niveau_diff', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prof_id', models.IntegerField()),
                ('prof_email', models.EmailField(max_length=254)),
                ('prof_nom', models.CharField(max_length=100)),
                ('prof_prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant_id', models.IntegerField()),
                ('etudiant_email', models.EmailField(max_length=254)),
                ('etudiant_nom', models.CharField(max_length=100)),
                ('etudiant_prenom', models.CharField(max_length=100)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50)),
                ('faculte', models.CharField(max_length=100)),
                ('annee_etude', models.CharField(max_length=50)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='cours.cours')),
            ],
            options={
                'unique_together': {('etudiant_id', 'cours')},
            },
        ),
    ]
