# Generated by Django 6.0 on 2025-12-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_id', models.IntegerField()),
                ('cours_titre', models.CharField(max_length=200)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('type', models.CharField(choices=[('COURS', 'Cours'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques')], max_length=10)),
                ('salle', models.CharField(max_length=50)),
                ('remarque', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
